# Generated by Django 4.2.4 on 2023-09-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="receiver_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiver_addresses",
                to="shipment.address",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="sender_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sender_addresses",
                to="shipment.address",
            ),
        ),
    ]
